# permissions for end users to edit graphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: graph-editor-role
rules:
- apiGroups:
  - tekton.visualise.tekton.visualise
  resources:
  - graphs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.visualise.tekton.visualise
  resources:
  - graphs/status
  verbs:
  - get
