# permissions for end users to view graphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: graph-viewer-role
rules:
- apiGroups:
  - tekton.visualise.tekton.visualise
  resources:
  - graphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.visualise.tekton.visualise
  resources:
  - graphs/status
  verbs:
  - get
