# permissions for end users to view TektonGraphs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: TektonGraph-viewer-role
rules:
- apiGroups:
  - tools.apps.tekton-visualise
  resources:
  - TektonGraphs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tools.apps.tekton-visualise
  resources:
  - TektonGraphs/status
  verbs:
  - get
